from django.urls import path

from .views import (
    CustomLoginView,
    CustomLogoutView,
    admin_course_detail,
    admin_course_registrations,
    admin_courses,
    admin_curator_detail,
    admin_curators,
    admin_academic_structure,
    admin_dashboard,
    admin_group_detail,
    admin_groups,
    admin_responses,
    admin_specialties,
    admin_student_detail,
    admin_student_import,
    admin_students,
    admin_vacancies,
    admin_vacancy_detail,
    curator_dashboard,
    curator_student_detail,
    curator_students,
    profile_edit,
    redirect_by_role,
    student_dashboard,
)

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('redirect/', redirect_by_role, name='redirect_by_role'),
    path('student/dashboard/', student_dashboard, name='student_dashboard'),
    path('student/profile/', profile_edit, name='profile_edit'),
    path('curator/dashboard/', curator_dashboard, name='curator_dashboard'),
    path('curator/students/', curator_students, name='curator_students'),
    path('curator/students/<int:student_id>/', curator_student_detail, name='curator_student_detail'),
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/students/', admin_students, name='admin_students'),
    path('admin/students/import/', admin_student_import, name='admin_student_import'),
    path('admin/students/<int:student_id>/', admin_student_detail, name='admin_student_detail'),
    path('admin/academic-structure/', admin_academic_structure, name='admin_academic_structure'),
    path('admin/groups/', admin_groups, name='admin_groups'),
    path('admin/groups/<int:group_id>/', admin_group_detail, name='admin_group_detail'),
    path('admin/specialties/', admin_specialties, name='admin_specialties'),
    path('admin/curators/', admin_curators, name='admin_curators'),
    path('admin/curators/<int:curator_id>/', admin_curator_detail, name='admin_curator_detail'),
    path('admin/vacancies/', admin_vacancies, name='admin_vacancies'),
    path('admin/vacancies/<int:vacancy_id>/', admin_vacancy_detail, name='admin_vacancy_detail'),
    path('admin/courses/', admin_courses, name='admin_courses'),
    path('admin/courses/<int:course_id>/', admin_course_detail, name='admin_course_detail'),
    path('admin/responses/', admin_responses, name='admin_responses'),
    path('admin/course-registrations/', admin_course_registrations, name='admin_course_registrations'),
]
