from django.urls import path

from .views import (
    CustomLoginView,
    CustomLogoutView,
    admin_course_detail,
    admin_course_registrations,
    admin_courses,
    admin_curator_detail,
    admin_curator_import,
    admin_curators,
    admin_academic_structure,
    admin_dashboard,
    admin_activity,
    admin_profile_edit,
    admin_group_detail,
    admin_group_import,
    admin_groups,
    admin_responses,
    admin_specialties,
    admin_specialty_detail,
    admin_support_ticket_detail,
    admin_support_tickets,
    admin_student_detail,
    admin_import_template_csv,
    admin_import_template_xlsx,
    admin_student_import,
    admin_students,
    admin_vacancies,
    admin_vacancy_detail,
    curator_dashboard,
    curator_profile_edit,
    curator_activity,
    curator_student_detail,
    curator_students,
    curator_course_registrations,
    curator_vacancy_responses,
    curator_support_tickets,
    profile_edit,
    redirect_by_role,
    student_dashboard,
    student_favorites,
    student_support_tickets,
    support_knowledge,
    public_support_ticket_create,
)

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('support/', public_support_ticket_create, name='public_support_ticket_create'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('redirect/', redirect_by_role, name='redirect_by_role'),
    path('student/dashboard/', student_dashboard, name='student_dashboard'),
    path('student/support/', student_support_tickets, name='student_support_tickets'),
    path('support/knowledge/', support_knowledge, name='support_knowledge'),
    path('student/profile/', profile_edit, name='profile_edit'),
    path('student/favorites/', student_favorites, name='student_favorites'),
    path('curator/dashboard/', curator_dashboard, name='curator_dashboard'),
    path('curator/activity/', curator_activity, name='curator_activity'),
    path('curator/students/', curator_students, name='curator_students'),
    path('curator/course-registrations/', curator_course_registrations, name='curator_course_registrations'),
    path('curator/vacancy-responses/', curator_vacancy_responses, name='curator_vacancy_responses'),
    path('curator/profile/', curator_profile_edit, name='curator_profile_edit'),
    path('curator/support/', curator_support_tickets, name='curator_support_tickets'),
    path('curator/students/<int:student_id>/', curator_student_detail, name='curator_student_detail'),
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/activity/', admin_activity, name='admin_activity'),
    path('admin/profile/', admin_profile_edit, name='admin_profile_edit'),
    path('admin/students/', admin_students, name='admin_students'),
    path('admin/students/import/', admin_student_import, name='admin_student_import'),
    path('admin/students/import/template/csv/', admin_import_template_csv, {'import_type': 'students'}, name='admin_student_import_template_csv'),
    path('admin/students/import/template/xlsx/', admin_import_template_xlsx, {'import_type': 'students'}, name='admin_student_import_template_xlsx'),
    path('admin/students/<int:student_id>/', admin_student_detail, name='admin_student_detail'),
    path('admin/academic-structure/', admin_academic_structure, name='admin_academic_structure'),
    path('admin/groups/', admin_groups, name='admin_groups'),
    path('admin/groups/import/', admin_group_import, name='admin_group_import'),
    path('admin/groups/import/template/csv/', admin_import_template_csv, {'import_type': 'groups'}, name='admin_group_import_template_csv'),
    path('admin/groups/import/template/xlsx/', admin_import_template_xlsx, {'import_type': 'groups'}, name='admin_group_import_template_xlsx'),
    path('admin/groups/<int:group_id>/', admin_group_detail, name='admin_group_detail'),
    path('admin/specialties/', admin_specialties, name='admin_specialties'),
    path('admin/specialties/<int:specialty_id>/', admin_specialty_detail, name='admin_specialty_detail'),
    path('admin/curators/', admin_curators, name='admin_curators'),
    path('admin/curators/import/', admin_curator_import, name='admin_curator_import'),
    path('admin/curators/import/template/csv/', admin_import_template_csv, {'import_type': 'curators'}, name='admin_curator_import_template_csv'),
    path('admin/curators/import/template/xlsx/', admin_import_template_xlsx, {'import_type': 'curators'}, name='admin_curator_import_template_xlsx'),
    path('admin/curators/<int:curator_id>/', admin_curator_detail, name='admin_curator_detail'),
    path('admin/vacancies/', admin_vacancies, name='admin_vacancies'),
    path('admin/vacancies/<int:vacancy_id>/', admin_vacancy_detail, name='admin_vacancy_detail'),
    path('admin/courses/', admin_courses, name='admin_courses'),
    path('admin/courses/<int:course_id>/', admin_course_detail, name='admin_course_detail'),
    path('admin/responses/', admin_responses, name='admin_responses'),
    path('admin/course-registrations/', admin_course_registrations, name='admin_course_registrations'),
    path('admin/support/', admin_support_tickets, name='admin_support_tickets'),
    path('admin/support/<int:ticket_id>/', admin_support_ticket_detail, name='admin_support_ticket_detail'),
]
