# Generated by Django 5.1.5 on 2026-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_academic_status_and_group_promotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="academic_status",
            field=models.CharField(
                choices=[
                    ("studying", "Обучается"),
                    ("academic_leave", "Академический отпуск"),
                    ("graduate", "Выпускник"),
                    ("inactive", "Отчислен"),
                ],
                default="studying",
                max_length=16,
            ),
        ),
    ]
