# Generated by Django 5.1.5 on 2026-05-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_supportticket_universal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('login', 'Проблема со входом'), ('profile', 'Ошибка в личных данных'), ('portfolio', 'Проблема с портфолио'), ('resume', 'Проблема с резюме'), ('courses', 'Проблема с курсом или записью'), ('vacancies', 'Проблема с вакансией или откликом'), ('no_account', 'Нет аккаунта'), ('wrong_password', 'Неверный пароль'), ('other', 'Другое')], default='other', max_length=32),
        ),
    ]
