# Generated by Django 5.1.5 on 2026-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_options_alter_supportticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='contact_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
