# Generated by Django 5.1.5 on 2026-05-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_template_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Компактный'), ('standard', 'Стандартный'), ('large', 'Крупный')], default='standard', max_length=32),
        ),
    ]
