# Generated by Django 5.1.5 on 2026-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resumesettings_photo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesettings',
            name='photo_source',
            field=models.CharField(choices=[('profile', 'Из профиля студента'), ('account', 'Фото из аккаунта'), ('custom', 'Отдельное фото для резюме'), ('hidden', 'Не показывать фото')], default='account', max_length=32),
        ),
    ]
